name: tramiteo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1+2

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  dio: ^4.0.4
  multiple_result: ^1.0.4
  pull_to_refresh: ^2.0.0
  flutter_html: ^2.2.0
  go_router: ^3.0.2
  webfeed: ^0.7.0
  flutter_riverpod: ^1.0.3
  webview_flutter: ^2.3.1
  url_launcher: ^6.0.17
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  nb_utils: ^4.4.10
  timeago: ^3.1.0
  eva_icons_flutter: ^3.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  cool_alert: ^1.1.0
  launch_review: ^3.0.1
  onesignal_flutter: ^3.2.8
  flex_color_scheme: ^4.1.1
  google_mobile_ads: ^1.0.1
  app_tracking_transparency: ^2.0.2+1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.1+1
  share_plus: ^3.1.0
  package_info_plus: ^1.4.0

  # flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/tramiteo-icon.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:

  
  color: "#ffffff"

  
  image: assets/img/tramiteo-icon.png

  
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0


flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
  
